### ISSUE TITLE
refactor: change writing interaction and factory methods

### ISSUE THREAD

**Issue by asiaziola** [warp-contracts/warp#176]
1. there should be only one `writeInteraction` method which - based on the gateway set during the initialization of warp - behave like current `writeInteraction` (in case of Arweave gw) or `bundleInteraction` (Warp gw) method. For warp gw `bundleInteraction` should be the default with an option to write interaction dirctly to arweave. API should be standarized (currently the structure of arguments passed to both methods differs). vrf/ar transfer should be an option.
2. `levelDbCached` should be renamed to `custom`
3. three factory methods:
a) forLocal - for ArLocal with an option to pass the whole Arweave instance or simple the port
b) forTesting - for Warp public testnet (Arweave instance should be set by default with an option to set custom)
c) forProd/forMainnet - for mainnet environment, add option to choose between warp and arweave gw (Arweave instance should be set by default with an option to set custom)

**Comment by ppedziwiatr** [comment]
additional change: https://github.com/warp-contracts/warp/issues/181
