### ISSUE TITLE
Unable to write contract exception

### ISSUE THREAD

**Issue by fuadop** [warp-contracts/warp#186]
Trying the below command throws an exception, `Unable to write Contract`.
![Screenshot from 2022-07-04 15-34-54](https://user-images.githubusercontent.com/65264054/177176004-c48837a5-e5a9-4107-b2c8-0fb434026c48.png)
![Screenshot from 2022-07-04 15-36-32](https://user-images.githubusercontent.com/65264054/177176059-7dad2b20-2712-41c1-9c49-b9e4e4fafe51.png)

**Comment by fuadop** [comment]
Any reasons why this could happen? How do I troubleshoot?

**Comment by asiaziola** [comment]
Hey @fuadop :) It's hard to tell without seeing the full code. 400 seems to be an error on Arweave side not linked to our implementation but of course we will try to help :)  Is it possible for you to share github repo? Maybe sth is wrong with the object you pass as an argument.

**Comment by fuadop** [comment]
Hey @asiaziola, Thanks for the feedback. 
Sure I can, It's on this draft PR - https://github.com/CommunityXYZ/community-js/pull/16/files

The line is here - https://github.com/CommunityXYZ/community-js/blob/c006774af0a744463ad411b8c5d91141228365a6/src/community.ts#L312-L321

**Comment by fuadop** [comment]
this is an example of the contract state (initState) being passed to the `warp.createContract.deployFromSourceTx` method -

```js
 {
      name: 'xxtestxx',
      ticker: 'xtx',
      balances: { QxH3kuDDlkjRqnH4vrFOkyiLbkuvg_2OdklTeRnZojc: 100 },
      vault: {},
      votes: [],
      roles: {},
      settings: [
        [ 'quorum', 0.5 ],
        [ 'support', 0.5 ],
        [ 'voteLength', 2000 ],
        [ 'lockMinLength', 720 ],
        [ 'lockMaxLength', 10000 ]
      ]
    }
 ```

**Comment by fuadop** [comment]
Just figured it out @asiaziola , The issue is from the quantity field of the transaction. it was integer instead of string.  See gateway validation for quantity field here - https://github.com/ar-io/arweave-gateway/blob/385ac37feca16e16af6d8095acaa3a90babc59bf/src/gateway/routes/new-tx/index.ts#L47-L51

**Comment by fuadop** [comment]
I'll just go ahead and stringify the quantity field of the transfer object being passed to the `deployContractFromSourceTx` method. Thanks for your help @asiaziola :heart:

**Comment by asiaziola** [comment]
i didn't do too much but I'm glad you figured it out :)
