### ISSUE TITLE
Warp overwrites `arweave.wallets.getBalance` method.

### ISSUE THREAD

**Issue by fuadop** [warp-contracts/warp#187]
Using warp, the `getBalance` method of `arweave.wallets` has a different implementation. It uses this implementation instead - https://github.com/warp-contracts/warp/blob/e0df511dc21b2e921132564cf1346aa4de220f7a/src/legacy/smartweave-global.ts#L71-L89

Therefore, I keep getting the following error when calling the method.

`Cannot read balance - active tx is not set.`

![Screenshot from 2022-07-04 17-50-27](https://user-images.githubusercontent.com/65264054/177195039-5034e357-36de-4826-b9f1-ff0919e7452d.png)
![Screenshot from 2022-07-04 17-50-20](https://user-images.githubusercontent.com/65264054/177195045-8759b2fa-e499-47a1-8b5a-fac9cf2ed7d7.png)
![Screenshot from 2022-07-04 17-50-12](https://user-images.githubusercontent.com/65264054/177195046-36344032-df46-4795-8b7d-52edba78b543.png)

**Comment by fuadop** [comment]
For a workaround, I ended up creating another arweave instance just to check wallet balances. 

![Screenshot from 2022-07-04 17-54-35](https://user-images.githubusercontent.com/65264054/177195204-1db33fbb-7033-410b-b341-818d7ca27915.png)

**Comment by fuadop** [comment]
Is that the right behavior for warp? or I am doing something wrong?

**Comment by fuadop** [comment]
You can refer to this PR - https://github.com/CommunityXYZ/community-js/pull/16 for info on how I am using Warp.

**Comment by asiaziola** [comment]
nah, it's not the right behaviour, it's a bug. 1.1.7 have it fixed :)
