### ISSUE TITLE
Error while running wasm intergration tests on Node 18

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#191]
`TypeError: The "source" argument must be an instance of Response or an Promise resolving to Response. Received an instance of Response`

Happens on Node 18.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/84311757/178274410-57c837d1-f334-40d6-b075-2a6e07cdf56e.png">

Might have sth. to do with the fact, that `fetch` is included in the Node 18 - and is not compatible with the fetch from `redstone-isomorphic`.

As a first step - update `undici-fetch` in the redstone-isomorphic and then update `redstone-isomorphic` in the SDK.
Remember to verify in Node 18!

**Comment by asiaziola** [comment]
seems to be a Jest problem, I upgraded it (withing redstone-isomorphic and typescript) and it works fine.
