### ISSUE TITLE
Feature request: deploySourceOnly

### ISSUE THREAD

**Issue by elliotsayes** [warp-contracts/warp#206]
Similar to `deploy`, but does not create a contract instance from the source, with initial state etc. This is useful in dApp models where many contracts are created from the same source, and so there is not need to create a contract when deploying the source.

Example usage:

```js
const srcTxId = await warp.createContract.deploySourceOnly({
  wallet,
  src: contractSrc,
});
```

The implementation can then be refactored so `deploy` just calls `deploySourceOnly` and `deployFromSourceTx` sequentially.

**Comment by elliotsayes** [comment]
If I get the go ahead, happy to take a stab at a PR

**Comment by ppedziwiatr** [comment]
not sure how would this play with deploying via Bundlr.. @asiaziola , what do you think?

**Comment by asiaziola** [comment]
I believe we already have it implemented :)) There's a `save` method which is then used by `deploy` method - https://github.com/warp-contracts/warp/blob/main/src/contract/deploy/impl/SourceImpl.ts#L31

It is not yet supported by bundlr, it should probably require some changes in the gateway, maybe I could start working on it next week.

**Comment by elliotsayes** [comment]
Completely missed it, sorry about that!
