### ISSUE TITLE
Broken images and hyperlinks in NPM package readme

### ISSUE THREAD

**Issue by duckception** [warp-contracts/warp#207]
Hey, I was reading through the [warp-contracts](https://www.npmjs.com/package/warp-contracts) NPM package readme and I've noticed that multiple images and hyperlinks are broken. To be exact, images of state evaluation diagram, warp transaction lifecycle and these hyperlinks are faulty:
- README-LEGACY
- SmartWeave Protocol
- Hyperlink to Arweave cache description
- Warp Gateway repository
- Warp Gateway API reference
- Migration guide from Arweave smartweave.js SDK to Warp SDK

Hope that helps! 😇

**Comment by ppedziwiatr** [comment]
Hey @duckception ! Thanks for the heads-up, we will update the docs :-)

**Comment by ppedziwiatr** [comment]
@asiaziola , what do we do about this? :-)

**Comment by ppedziwiatr** [comment]
fixed
