### ISSUE TITLE
Release candidate does not work in browser.

### ISSUE THREAD

**Issue by dabit3** [warp-contracts/warp#209]
As I mentioned in #208, installing as per docs installs version 1.1.14, but `WarpFactory` is not available, so instead I have upgraded to the release candidate `v1.2.0-rc.1`

This works in a node.js environment, but when trying to use it in the browser, I'm getting an error:

```
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/tslog/dist/esm/LoggerWithoutCallSite.js
./node_modules/tslog/dist/esm/index.js
./node_modules/warp-contracts/lib/cjs/logging/node/TsLogFactory.js
./node_modules/warp-contracts/lib/cjs/logging/index.js
./node_modules/warp-contracts/lib/cjs/index.js
./pages/index.js

https://nextjs.org/docs/messages/module-not-found
wait  - compiling /_error (client and server)...
error - ./node_modules/tslog/dist/esm/LoggerHelper.js:2:0
```

I've tried both `esm` and `commonjs`, neither seem to be working.

**Comment by ppedziwiatr** [comment]
Related to https://github.com/warp-contracts/warp/pull/190

**Comment by ppedziwiatr** [comment]
Hey @dabit3 . Please verify the new version - `1.2.0-rc.2`.
We now have a dedicated repo that verifies if SDK works for different web bundlers and in node (.js, .mjs, .ts) - https://github.com/warp-contracts/bundlers#readme

In case of next.js - https://github.com/warp-contracts/bundlers#Next

**Comment by dabit3** [comment]
Hey, just tried this out, works perfectly! When do you think you all will be releasing it?

**Comment by ppedziwiatr** [comment]
> Hey, just tried this out, works perfectly! When do you think you all will be officially releasing it?

We will probably promote it to main and release as official version either this or at the beginning of next week - one last enhancement that we want to include in RC is https://github.com/warp-contracts/warp/issues/213

**Comment by dabit3** [comment]
Awesome! Thank you.
