### ISSUE TITLE
Allow to enable Vrf in testing environments

### ISSUE THREAD

**Issue by noomly** [warp-contracts/warp#222]
Currently it is strictly required to use the Sequencer if we want to use Vrf, which makes it impossible to test the API locally or on the testnet. Allowing a non-verifiable version only on the testnet and locally would make developing/testing contracts making use of it a lot easier.

**Comment by ppedziwiatr** [comment]
Done, tested in https://github.com/warp-contracts/warp/commit/90f96511a4b1c8916541c68a92bc62eba3a70890#diff-fc8f73adefb2d436efca49ad1f9867b9ba3e40610db08a6c574ccbb92565ca74R142

I just need to perform some more tests in browser env - if everything will be fine, it should be released in a day or two.

**Comment by ppedziwiatr** [comment]
Released in `1.2.7`
