### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'randomUUID') - Warp 1.2.7

### ISSUE THREAD

**Issue by luckyr13** [warp-contracts/warp#226]
Hello guys! I was updating my dapps to the new Warp version 1.2.7 and I noticed an error. The error happens when trying to use the `readState` function like in the example from the README file:

```js
const { sortKey, cachedValue } = await contract.readState();
```
If I call the `readState` function from my dapp I get this error:

```
TypeError: Cannot read properties of undefined (reading 'randomUUID')
    at new ContractCallRecord (ContractCallRecord.js?68e4:11:1)
    at new HandlerBasedContract (HandlerBasedContract.js?8724:93:1)
    at Warp.contract (Warp.js?b82a:40:1)
    at WarpContracts.readState (WarpContracts.ts?328c:67:1)
    at _callee$ (HomePage.vue?a457:50:1)
```
![errorWarp](https://user-images.githubusercontent.com/7094823/191137249-ce166df7-2be5-4160-aeb6-d0cdbaa3f378.png)

If I track the error it ends on the next line:

![cryptoError](https://user-images.githubusercontent.com/7094823/191137319-1272ed2b-f88e-4182-9291-123e2200fb6f.png)

My question is if you have any suggestion to avoid this error? I'm already excluding the `crypto` library in my project bundle.

Thanks in advance!

**Comment by luckyr13** [comment]
Today I updated warp contract to the latest version 1.2.10 and the problem is gone. Thank you guys, you rock!!

**Comment by ppedziwiatr** [comment]
yeah, that was..uhm..my mistake ;-) , described here: https://discord.com/channels/786251205008949258/816685554329583707/1021740379256659999

**Comment by luckyr13** [comment]
Hey ppe, no problem at all! Thanks for the quick fix! Btw the current Warp Contracts library works incredibly fast, congratulations 🎊
