### ISSUE TITLE
Contract state changes after it's returned

### ISSUE THREAD

**Issue by arcj0** [warp-contracts/warp#227]
readState() seems to be returning an earlier version of the contract state before all interactions are processed.

An example of this issue can be seen in the following repo:
https://github.com/aftrmarket/vue-contract-test

**Comment by ppedziwiatr** [comment]
@arcj0 Which exact point from your example is showing the issue?

**Comment by ppedziwiatr** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/84311757/192167863-5b59c2bf-a567-4778-8ed4-ef94fa3e7933.png">

**Comment by ppedziwiatr** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/84311757/192169836-42b44157-e70e-4f2e-9ec3-6a4649170e65.png">

**Comment by ppedziwiatr** [comment]
Fix in the contract code: https://github.com/warp-contracts/vue-contract-test/commit/91fa18d802be3a926845add84b3b1fbe4e15f4f3#diff-03feeffc0d8e9de0db643a183d0b3cffe02c8229c84d06b575a51fe907d6c312
