### ISSUE TITLE
Possible issue with IW on Warp 1.2.0

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#233]
reported by @twilson63 on Discord.
For reference:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/84311757/193240105-ca24b135-1ec6-4dcf-9e57-7d9348f80e1b.png">

<img width="727" alt="image" src="https://user-images.githubusercontent.com/84311757/193240321-91ddd74e-08bd-43f0-9b3f-e1ad19dceb2d.png">

https://github.com/twilson63/bug-report-warp

**Comment by ppedziwiatr** [comment]
So I'm in the process of analyzing what is going on..(a disclaimer - it's kinda difficult to quickly wrap my head around such scenarios - the contracts themselves have ~600 and ~150 loc and they are in a "compiled" form..).
I need to fully understand what the contracts are doing and how they interact with each other in the test case.

Now 
From your test - when the 
```ts
await asset.writeInteraction({
    function: "createOrder",
    pair: [barContract, assetContract],
    qty: 10000,
    transaction: result.originalTxId,
  }, {strict: true});
```

and then 
`const assetResult = await asset.readState();`

is being called, the logs from contracts are as follow (I've added some in the contracts):

```
ASSET readState
ASSET::CreateOrder
ASSET::CreateOrder before claim balance
ASSET::CreateOrder:claimBalance - before internal write
BAR::claim
ASSET::CreateOrder:claimBalance - after internal wriate
ASSET::CreateOrder after claim balance
BAR::transfer {
  target: 'lbhCqadjz6OGLDUzYyUd-YGZ3iEqSpdOkkYt5-_3_-I',
  quantity: 9800
} - I DON'T CURRENTLY UNDERSTAND WHAT IS TRIGGERING THIS TRANSFER ON A BAR CONTRACT.
BAR::transfer - caller balancer validation { callerBalance: null, quantity: 9800 }
BAR::transfer - caller balance validation failed
ASSET::CreateOrder:refundTransfer before internal write transfer AnHVDu4h_W0SBhhPaISmbk-EQ5bsyEqFgcQrsyp3VMA
BAR::transfer {
  target: 'mTe_4T5CxFr2plT5vvlOEFuII0T9LTwjnKEG7Dkcz_Q',
  quantity: 10000
}
BAR::transfer - caller balancer validation { callerBalance: null, quantity: 10000 }
BAR::transfer - caller balance validation failed
```

And the resulting error message for this interaction is:
```json
errorMessages: {
      'wKcCK3ewP7WDF2IvGdetqh-aEDlr5hVkiU9_cWHEngw': 'Internal write auto error for call [{"from":"bebeT2JMNK5UXfWO3R21PPohe2pQ0H0XanzOPZbkyNU","to":"wfnpEzPPCW9INAHIV8_aNmFUDtovPnslBJw3txEOrPo","input":{"function":"transfer","target":"4Pm12dZcY42TSmgt-23DmKMWRYvULZW9KVmf7P479-k","qty":10000}}]: Caller balance not high enough to send 10000 token(s).'
}
```

which is probably a reason why the whole test fails (as the "createOrder" interaction fails in general).

One things I don't understand - is where this first transfer on bar contract is coming from (during the evaluation of the "CreateOrder" of the asset contract - I've marked this in the pasted logs - I'll analyze this further though, but maybe you could give me a hint?

**Comment by twilson63** [comment]
So the `createOrder` is part of Verto Flex; I don't understand all the internals, but here is the repository for the module

https://github.com/useverto/flex

I am just a user of this component, for internal workings it might be best to discuss with Tate or Marton of Component Labs
I know it works fine on warp 1.1.14 but not on 1.2.x

**Comment by ppedziwiatr** [comment]
I see, so I guess I'll need to first fully understand how flex works :-)

**Comment by ppedziwiatr** [comment]
From Discord:

Hey again. I believe the "flex" contract (or Bar or whatever - I'm  slowly loosing track what is what) is broken. 
https://github.com/warp-contracts/bug-report-warp/commit/d0595c698c5b0162d7ca6a24fad0f225e8bea77a#diff-064d8d9821ce90c7f031f70db6b1beb85ae93e915fe355323bd8189ebc025a27R153
undefined + number = NaN in JS.
With the above fix the test passes correctly.

The "claim" internal write from asset to bar was causing NaN to be set in the balances map - for the above reason.
```
ASSET::CreateOrder:claimBalance - before internal write
BAR::claim
BAR::claim:claimable_obj {
  obj: {
    from: 'biCMe9SvILqwCYutedN4UPi7i8BKM5wZGufUyx9lRwM',
    to: 'Xv0kFB0cKTwzsTF8mTb7B0cii096UFMpIxoOlGa9N6o',
    qty: 10000,
    txID: 'tmWrWDa9gpECQqs1e7TMdsiiLEHBRZlUGbwtoy2VvxA'
  },
  caller: 'Xv0kFB0cKTwzsTF8mTb7B0cii096UFMpIxoOlGa9N6o',
  callerBalance: undefined
}
ASSET::CreateOrder:claimBalance - after internal write {
  balances: {
    biCMe9SvILqwCYutedN4UPi7i8BKM5wZGufUyx9lRwM: 990000,
    'AsuUQfu-eEX50jfpYO2tCOjKV_ezcy3Hb5fL9s5AVWg': 1000000,
    Xv0kFB0cKTwzsTF8mTb7B0cii096UFMpIxoOlGa9N6o: NaN
  },
  canEvolve: true,
  claimable: [],
  claims: [ 'tmWrWDa9gpECQqs1e7TMdsiiLEHBRZlUGbwtoy2VvxA' ],
  creator: 'biCMe9SvILqwCYutedN4UPi7i8BKM5wZGufUyx9lRwM',
  divisibility: 6,
  name: 'BAR',
  settings: [ [ 'isTradeable', true ] ],
  ticker: 'BAR'
}
```
 
This in turn was causing the next internal write from asset to bar to fail
```
BAR::transfer - caller balancer validation { callerBalance: null, quantity: 9800 }
BAR::transfer - caller balance validation failed
ASSET::CreateOrder:catch ContractError: Internal write auto error for call [{"from":"Xv0kFB0cKTwzsTF8mTb7B0cii096UFMpIxoOlGa9N6o","to":"-zBCBPMsyVCecFJHpMgSu68_0h628yJHIfNf33bsAxw","input":{"function":"transfer","target":"AsuUQfu-eEX50jfpYO2tCOjKV_ezcy3Hb5fL9s5AVWg","qty":9800}}]: Caller balance not high enough to send 9800 token(s).
    at swGlobal.contracts.write (/Users/piotrpedziwiatr/projects/bug-report-warp/node_modules/warp2/lib/cjs/core/modules/impl/handler/AbstractContractHandler.js:63:23)
```

The reason it "worked" in 1.1.4 is probably because the results of the internal writes were not properly verified for each internal write.
1.2.0 by default throws a ContractError from the outer transaction whenever the internal write fails - in order to remove the need to write the boilerplate check:
```
if (result.type !== "ok") {
      throw new ContractError(`Oh no, internal write have exploded`);
    }
```

**Comment by ppedziwiatr** [comment]
I will analyse why exactly it "works" in 1.1.4 on Monday.
