### ISSUE TITLE
feat: add option to load Sequencer transactions via Arweave loader

### ISSUE THREAD

**Issue by kevin-zhangzh** [warp-contracts/warp#236]
The default Arweave interactions loader implementation skips the bundled interactions.                                                             
 Is it possible to implement a arweave loader that loads bundle type transactions?

**Comment by ppedziwiatr** [comment]
Example contract https://sonar.warp.cc/#/app/contract/XIutiOKujGI21_ywULlBeyy-L9d8goHxt0ZyUayGaDg

**Comment by ppedziwiatr** [comment]
Implemented on our side, but while testing this I've noticed an issue with indexing bundle data-items by the arweave.net gateway - I guess I've opened a small Pandora's box ;-)
ar.io is already working towards fixing this issue.

for reference: https://github.com/ar-io/arweave-gateway/issues/3#issue-1404809078

**Comment by ppedziwiatr** [comment]
@Tadeuchi , we need to return back to this.

TODO:
1. rebase to main
2. verify if the owner is set properly (probably it is not)
3. prepare an example - deploy a contract, write 100 interactions via Sequencer, show how to load them directly from Arweave.

**Comment by ppedziwiatr** [comment]
implemented in https://github.com/warp-contracts/warp/pull/368
