### ISSUE TITLE
Abstract transaction signing logic

### ISSUE THREAD

**Issue by jakub-wojciechowski** [warp-contracts/warp#237]
Currently we support only the Arweave native way of signing transactions. 
However, this introduces a lot of frictions as most of the people don't have the necessary plug-ins like ArConnect. 

As we're forwarding the transactions using bundlr we could use a different signing scheme like the ethereum based ECDSA. 
This will allow any user that has eth compatible wallet (like metamask) to publish Warp transactions. 

Plugins popularity:
ArConnect users ~ 10k
Metamask (2022) ~ 30M

**Comment by ppedziwiatr** [comment]
ok, but how will then identify the users - e.g. in ERC-20 token - in the balances map? some of them will use arweave wallet address, some eth wallet address, etc?

**Comment by ppedziwiatr** [comment]
Also, keep in mind that:
1. it is user who signs the "original" transaction (either contract deployment transactions or contract interactions)
2. Warp only signes the "bundled transaction" - i.e. the transaction that contains/wraps the original user transaction.

But the whole SmartWeave protocol, the contract code, the SmartWeave "globals", etc., sees only the "original" - user transactions - that is signed by the Arweave wallet.

**Comment by asiaziola** [comment]
yesss
