### ISSUE TITLE
feat: allow http keep alive 

### ISSUE THREAD

**Issue by jarrvis** [warp-contracts/warp#245]
For server side usage it would be nice to keep alive http connection.
E.g here:
https://github.com/warp-contracts/warp/blob/c1bfb2f58518a4369c044c84fabcb7d070d4e092/src/contract/HandlerBasedContract.ts#L293

or here:
https://github.com/warp-contracts/warp/blob/c1bfb2f58518a4369c044c84fabcb7d070d4e092/src/contract/deploy/impl/DefaultCreateContract.ts#L117
(since some users create contracts dynamically)

Is it possible with current api? Could we externalize fetch options to e.g. use custom configuration of http agent?

**Comment by ppedziwiatr** [comment]
Hey, nope, it's not possible with current api. I'm thinking about adding an option to register in warp instance some function `(x: RequestInfo | URL) -> {}` - that would take the original request data as parameter and return object with options, that should be attached to the fetch.

We could probably use here the new plugin API - https://github.com/warp-contracts/warp/blob/rc/evm-signature/src/core/WarpPlugin.ts - the plugin would take `RequestInfo | URL` as an input and return `Partial<RequestInit>`.

It could be then registered with
```
warp.forMainnet().use(new FetchOptionsPlugin())
```

Last but not least - the SDK will need to verify whether such plugin was registered - and if so, call it to determine the options and attach them to fetch.

@asiaziola , such a great task for you!

**Comment by jarrvis** [comment]
Hi @asiaziola, 👏👏👏
this is great!

For server side keep-alive usecase the plugin impl uses:
```javascript
fetchOptions = {
   agent: new http.Agent({
     keepAlive: true
   })
};
```

Debugging SSL shows:

HTTPS 97208: createConnection [Object: null prototype] {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'd1o5nlqr4okus2.cloudfront.net',
  port: 443,
  hostname: 'd1o5nlqr4okus2.cloudfront.net',
  hash: null,
  search: '?contractId=ECzhNQQBwAf3TV0r4rDyr6zglCzWha57VoFyNmqMnsQ&from=000001081630%2C1671580571027%2C3005273068d18d0699e446a9c12dfbc28a786c5012f2e1c8e6680423043c3efd&page=1&fromSdk=true&confirmationStatus=not_corrupted',
  query: 'contractId=ECzhNQQBwAf3TV0r4rDyr6zglCzWha57VoFyNmqMnsQ&from=000001081630%2C1671580571027%2C3005273068d18d0699e446a9c12dfbc28a786c5012f2e1c8e6680423043c3efd&page=1&fromSdk=true&confirmationStatus=not_corrupted',
  pathname: '/gateway/v2/interactions-sort-key',
  path: null,
  href: 'https://d1o5nlqr4okus2.cloudfront.net/gateway/v2/interactions-sort-key?contractId=ECzhNQQBwAf3TV0r4rDyr6zglCzWha57VoFyNmqMnsQ&from=000001081630%2C1671580571027%2C3005273068d18d0699e446a9c12dfbc28a786c5012f2e1c8e6680423043c3efd&page=1&fromSdk=true&confirmationStatus=not_corrupted',
  method: 'GET',
  headers: [Object: null prototype] {
    Accept: [ '*/*' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ]
  },
  agent: Agent {
    _events: [Object: null prototype] {
      free: [Function (anonymous)],
      newListener: [Function: maybeEnableKeylog]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    defaultPort: 443,
    protocol: 'https:',
    options: [Object: null prototype] { keepAlive: true, path: null },
    requests: [Object: null prototype] {},
    sockets: [Object: null prototype] {
      'd1o5nlqr4okus2.cloudfront.net:443:::::::::::::::::::::': []
    },
    freeSockets: [Object: null prototype] {},
    keepAliveMsecs: 1000,
    **keepAlive: true,**
    maxSockets: Infinity,
    ...
}
