### ISSUE TITLE
fix: leveldb not close when stop program

### ISSUE THREAD

**Issue by zyjblockchain** [warp-contracts/warp#250]
when I restart program and got those errors
<img width="939" alt="image" src="https://user-images.githubusercontent.com/40423181/200338909-39e5ae84-dd9f-4440-88a8-5527bec71782.png">
I think it is program can not correct to close level db

this link could get more info
https://github.com/Level/classic-level#dbclosecallback

**Comment by ppedziwiatr** [comment]
Hey @zyjblockchain , I've released `1.2.17`, where I'm forcing the leveldb to open.

But in general - I would suggest trying out the different - LMDB - cache implementation - https://github.com/warp-contracts/warp-contracts-lmdb#warp-contracts-lmdb-cache

I'm using the lmdb in our cache implementation (with many concurrent evaluators working at the same time) - and it works without issues.

Or you can create your own implementation - according to your need - you can take the `warp-contracts-lmdb-cache` as an example - it is simply a `SortKeyCache` interface implementation.
