### ISSUE TITLE
Error: Unable to retrieve transactions. Warp gateway responded with status undefined.

### ISSUE THREAD

**Issue by luckyr13** [warp-contracts/warp#251]
Hello warp-contracts team! Today I updated warp-contracts in my app to the latest version `1.2.14` but I'm getting this error when trying to read the state of any contract: 
`Unable to retrieve transactions. Warp gateway responded with status undefined.`

It seems that the library is trying to connect to this localhost endpoint: 
`GET http://localhost:5666/gateway/v2/interactions-sort-key?contractId=ewepANKEVffP0cm_XKjwTYhSBqaiQrJbVrCcBiWqw-s&from=000001049596%2C1667455545670%2C76909576947e8b8131846abdffdd64f9f885bec1d2017e37dfff4400543f909a&page=1&fromSdk=true&confirmationStatus=not_corrupted net::ERR_CONNECTION_REFUSED`

What could be the problem? Thanks in advance for your time 🙏

**Comment by twilson63** [comment]
FWIW, I was getting the same problem, did not have time to investigate, I had to rollback 1.2.13

**Comment by asiaziola** [comment]
@luckyr13 @twilson63 should be fixed in 1.2.15 :)
