### ISSUE TITLE
feat: Keep a changelog

### ISSUE THREAD

**Issue by DougAnderson444** [warp-contracts/warp#254]
Feature request to add a version changelog, at minimum of breaking changes

(like switching `warp.testing.generateWallet()` to `warp.generateWallet()`

**Comment by ppedziwiatr** [comment]
Hey, from now on we will create a proper release for each new SDK version.

Sorry for the latest change in `generateWallet`, we wanted to simplify the API, but we should probably leave the old version for some time - with a 'Deprecated' annotation.

https://github.com/warp-contracts/warp/releases
