### ISSUE TITLE
feat: make local and production API the same

### ISSUE THREAD

**Issue by DougAnderson444** [warp-contracts/warp#260]
Is it possible to make the `local` api Tags the same as `mainnet`?

For example, when I save a contract to mainnet, Warp uses Tag `Uploader-Contract-Owner` but when it's local Warp uses the legacy api SmartWeave Tags. That means Warp users need two different configurations depending on what network they are using, to make `graphql` searches work.

**Comment by ppedziwiatr** [comment]
I believe the above issue has been solved by the native nested bundle feature - we no longer need to manually wrap original transaction and use dedicated tags.
