### ISSUE TITLE
feat: contract evaluation manifest

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#264]
The contract deployment transaction should contain information about which options should be used to evaluate the contract (e.g, `allowBigInt`, `internalWrites`, etc) - stored in tags.

The SDK should automatically set all the required evaluation options based on this configuration.

The SDK should also WARN if the contract is not being evaluated with required options.

One potential issue here to solve is that each contract that takes part in the execution may require different evaluation options - what if - for example - parent contract 'blocks' the internal writes, but the child contract (e.g. the one whose parent contract is reading the state via `readContractState`) allows internal writes?

Currently - the whole evaluation inherits the evaluation options from the root contract settings.

**Comment by ppedziwiatr** [comment]
The rules:
https://github.com/warp-contracts/warp/blob/ppe/grrrrrrrrrrrr/src/contract/EvaluationOptionsEvaluator.ts#L23

The tests showing how the most crucial options work:
https://github.com/warp-contracts/warp/blob/ppe/grrrrrrrrrrrr/src/__tests__/unit/evaluation-options.test.ts#L124

**Comment by ppedziwiatr** [comment]
released in 1.2.35

**Comment by jakub-wojciechowski** [comment]
Let's add new evaluation modes for:
1) Only Arweave L1
2) Only Sequencer/Bundles (L2)
3) Mix of both (L2 for speed + L1 for trustless exits)

**Comment by jakub-wojciechowski** [comment]
It'll be great to consider signalling evaluation options also for existing contracts (maybe sth similar to the evolve mechanics).

**Comment by ppedziwiatr** [comment]
What is the use case and which projects requested these features?

We spoke few months ago about restricting to only L1 or only sequencer (ar.io suggested such feature), but - afair - you were against it.
Also - I still don't see a real use case for point 3 (at least not in the Arweave ecosystem) - and it really adds a lot of complexity.

In general - this also adds some complexity to the interaction writing process (e.g. all interactions on mainnet warp instance - according to your request - are now sent by default to the sequencer. We would now need to first verify the contract manifest and choose the right method (not sure what to do in case of point 3)).
Additionally - the sequencer would now also need to verify if the contract supports it - i.e. it would need to first load contract data and verify its manifest - this will slow down the processing and sequencer's TPS.

btw., please don't reopen old, already implemented issues.
new features, new bugs, etc. = new issue.

**Comment by ppedziwiatr** [comment]
> Let's add new evaluation modes for:
> 
> 1. Only Arweave L1
> 2. Only Sequencer/Bundles (L2)
> 3. Mix of both (L2 for speed + L1 for trustless exits)

@Tadeuchi started development today.

I have no idea how to solve the 'evolve' for the contract manifest (and I really don't want to further complicate the SDK for some 'potential' use cases) - so we will stick only with initial deployment for now.

**Comment by ppedziwiatr** [comment]
sourceType added to the contractManifest within https://github.com/warp-contracts/warp/commit/2c23f19f1f14af407f0ae72e13e52a18f9ac19c1
