### ISSUE TITLE
perf: deadlocks with isolated-vm

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#272]
Probably related to
https://github.com/laverdet/isolated-vm/issues/302
https://github.com/laverdet/isolated-vm/issues/307
https://github.com/laverdet/isolated-vm/issues/321

Reproducible example:

```ts
/* eslint-disable */

import {defaultCacheOptions, LoggerFactory, WarpFactory} from "warp-contracts";
import {IvmPlugin} from "warp-contracts-ivm-plugin";

LoggerFactory.INST.logLevel('debug');
// LoggerFactory.INST.logLevel('none', 'DefaultStateEvaluator');
const logger = LoggerFactory.INST.create('ivm-example');

async function main() {
  const contractTxId = 'XIutiOKujGI21_ywULlBeyy-L9d8goHxt0ZyUayGaDg';

  const warp = WarpFactory
    .forMainnet({...defaultCacheOptions, inMemory: true})
    .use(new IvmPlugin({}));

  const result = await warp
    .contract(contractTxId)
    .setEvaluationOptions({
      allowBigInt: true,
      internalWrites: true,
    })
    .readState();

  console.log(result.cachedValue.validity);
}

main().catch((e) => console.error(e));
```

In my case it always hangs at 1201. interaction:
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/84311757/204060930-2b2949a4-0f16-40f7-a0f3-02d81e856564.png">

We need to generate a stacktrace and report this to library authors.

**Comment by ppedziwiatr** [comment]
Reading the above issues, it is probably also worth experimenting with isolated-vm version `4.3.6` (which probably requires downgrading the node to ver. 16).

If that won't help - try to temporarily remove the isolate disposal code - https://github.com/warp-contracts/warp-contracts-plugins/blob/main/warp-contracts-ivm-plugin/src/IvmHandlerApi.ts#L85

**Comment by janekolszak** [comment]
Downgrading to node 16.18.1, warp 12.30, isolated-vm in 4.3.6 works fine

**Comment by janekolszak** [comment]
https://github.com/laverdet/isolated-vm/issues/330

**Comment by ppedziwiatr** [comment]
https://github.com/laverdet/isolated-vm/issues/330#issuecomment-1353254772 @janekolszak ?
although not sure if we want to use the isolated-vm...

**Comment by ppedziwiatr** [comment]
Let's stick with VM2 + separate node process (supplied by the bullmq's sandboxed processors).

With the possible addition of the https://github.com/taskforcesh/bullmq/issues/1555 - it should be 'good enough' for now.

In the future - consider switching to SES.
