### ISSUE TITLE
feat: add option to register bundled contract transaction

### ISSUE THREAD

**Issue by asiaziola** [warp-contracts/warp#277]
In order to deploy 'real atomic NFTS' we need to allow users to bundle contract transactions on their own instead of Warp's behalf. Bundlr response/bundlr id should be then passed to a dedicated method in the sdk which will post it to Warp Gateway so it can be indexed (without uploading to bundlr by Warp).

Bundlr team needs to enable a dedicated endpoint which will return contract's metadata so we can easily verify transaction in the Gateway (e.g. if it contains proper contract tags). Most probably - when they added - we just need to receive bundlr id and hit this endpoint to get further data.

Task for now: push the bundlr team!

**Comment by ppedziwiatr** [comment]
released in 1.2.39
