### ISSUE TITLE
feat: contract deployment via nested bundles

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#293]
Deploy contract via a nested bundle (i.e. user creates a data-item and sends to Warp Gateway. The warp gateway wraps it in its own bundle and posts to Bundlr - this way the original data-item will be properly indexed by the arweave.net gateway).
Note that this requires changes in the warp gateway. The current endpoint should not change! (add a new endpoint - also, set a proper deployment-type - e.g. 'nested-bundle').
Note that this probably required adding either arbundles or bundlr-js library to the deployment plugin code - which will probably cause some issues in browsers....

**Comment by asiaziola** [comment]
A dedicated plugin should be created for contract deployment, it will use arbundles library underneath to create a contract data item.

1. arbundles library should be tested in the browser env to check any potential problems, most probably it will not work properly, some solutions to overcome this:
- plugin can use its own bundler to attach polyfills required by arbundles lib
- arbundles can be forked and adapted to our needs (use only the methods which are needed for the deployment and adjust it to node/web env), **problem:** if arbundles changes, arbundles fork needs to be upgraded as well
- create a PR in arbundles lib with proper changes

2. we need to preserve current options for signing the transactions (with Arweave/Ethereum wallet in browser and in node), arbundles exposes a `Signer` interface (https://github.com/Bundlr-Network/arbundles/blob/master/src/signing/Signer.ts) and couple of implementations (e.g. `ArweaveSigner`, `EthereumSigner`), it seems not to work in browser - need to check how it behaves and maybe create proper implementations

3. create a dedicated endpoint in the Warp Gateway - it will receive a data item, uploads it to Bundlr and index - proper verifications need to be added (data item verification. contract tags verification)

4. create a deployment plugin which will be used in the SDK by the client who'd like to deploy a contract, SDK will delegate deployment methods implementations to this plugin (include all the deployment methods)
