### ISSUE TITLE
feat: contract decorators

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#297]
..as a way of "extending" base contract code.

Problem: currently there is no standard way of extending a contract code.
Example: if one wants to create PST contract (and add some features on top), all the code of the PST contract has to copied into the new contract.

Decorator example:
```js
export const handle = withSessionWallets(follows);

/**
 * 
 * handler (state, {input, caller}) => {state})
 */
function withSessionWallets(handler) {
    return async (state, action) => {
        const input = action.input;

        const sessions = deepCopy(state['sessions'] || {});

        switch (input.function) {
            case 'setSession':
                return setSession(action, input, sessions, state);
            default:
                action.caller = getMasterCaller(input.session, sessions, action.caller);

                // we wan't to be sure that lower contract won't override our state.
                // lower contract has access to state, however he can't modify it 
                const { state: newState } = await handler(state, action)
                return { state: { ...newState, sessions } }
        }
    }
}
```

**Comment by koonopek** [comment]
decorator: `withSessionWallets`
handler `follows` - typical warp handle function

Problem described by @ppedziwiatr:
1. We have to create `deepCopy` of decorator state to avoid situation where decorator state is overiden in contract which is being decorated. DeepCopy is expensive computation.
2. Classhing namespaces, names from one decorator can override another one, for example: `withSessionWallet(follows)`
`follows(profileId) where profileId = sessions` could override `sessions` key from `wtihSessionWallets` decorator
3. How to enable good practice(which will avoid 1. and 2.) by design?

**Comment by ppedziwiatr** [comment]
Another issue:
4. How to force proper structure in the initial states (i.e. the one required by the decorators). Or do we simply assume that decorators will be written in a 'defensive' way and manually initialize required structures?
Imho a decorator (which will be probably a separate npm library) could have a separate method for preparing the initial state - that should be called during the contract deployment (via warp.deploy)

**Comment by ppedziwiatr** [comment]
Re. point 2 - I believe we should introduce a naming convention `<decorator-name>:<function-name>` - sth. similar to how Akord name their functions:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/84311757/208244434-470e5ea9-f845-4719-94ca-3de3c86028a7.png">

**Comment by koonopek** [comment]
So i have some proposition which is not, perfect but solves:
1. + We are using namespaces, so we don't have to copy state
2. Same as above
3. It is hard to judge, developer has to remember about passing additional flag - `finished` if the contract should exit, before calling next fn's. And generally, code is getting more complicated
4. I think it can be achieved with this example
https://github.com/warp-contracts/expermients-decorators/blob/f146d9ccf9168e239d1700ad47ddf10c10d538e3/main.js#L1-L111

**Comment by koonopek** [comment]
Here is full example: with `Pst`: https://github.com/warp-contracts/expermients-decorators
