### ISSUE TITLE
feat: documentation for what is Injected in JS runtime

### ISSUE THREAD

**Issue by koonopek** [warp-contracts/warp#298]
Maybe, i don't know where to search for it.

I found it in code base eventually, but still some explanation would be helpful :)

I'm not sure, if I should use it, if it's in legacy dir:
https://github.com/warp-contracts/warp/blob/main/src/legacy/smartweave-global.ts

**Comment by asiaziola** [comment]
it's in legacy dir as it is inherited from original SmartWeave implementation, you can read some more about it here https://github.com/ArweaveTeam/SmartWeave/blob/master/CONTRACT-GUIDE.md#smartweave-global-api

I'll try to add info about it to the SDK docs and to the Warp Academy next week.

**Comment by koonopek** [comment]
Great! Thanks `SmartWeave.block.timestamp` is in seconds or milliseconds?
