### ISSUE TITLE
feat: constructor (initial state)

### ISSUE THREAD

**Issue by koonopek** [warp-contracts/warp#323]
Let's assume that we have contract like this:
```javascript
handle(...)

function first(state, action) {
    if(action.caller == ALICE) {
       return {state: [...state, `${ALICE} was here`]}
    }
}

function second(state ,action) {
    if(action.caller == BOB && state.includes(`${ALICE} was here`) {
       return {state: [...state, `${BOB} was here`]}
    }
}
```

How I can be sure, that ALICE really called first function, if it can be just initialised in this way with `initState` option.
```javascript
deploy(src, {initState: [`${ALICE} was here}`] })
```
This two ^^ examples are NOT differentiable from smart contract perspective.

To easiest solution would be to allow disabling initialState for some contract IMHO

**Comment by koonopek** [comment]
Maybe there is solution, however i don't see at the time of writing

**Comment by ppedziwiatr** [comment]
Let's look at this from another perspective.

Let's say that initial state is empty, but ALICE is putting into state sth like:
```
if(action.caller == ALICE) {
       return {state: [...state, `${BOB} was here`]}
    }
```
- what now? :-) 
How can you tell that it wasn't BOB who had set this value?

I believe the only way in this case would be to sign each new change with the caller wallet?
And then, each time you need to use this data in the contract - first validate the signature.

**Comment by ppedziwiatr** [comment]
> Every one who has read code, and know that it can't be changed (assumptions on blockchain trust).

Well, the same way you can verify the initial state...(as it is kept in the contract deployment transaction).

But...I guess I understand your point of view...we should probably define sth like 'init/constructor' function in the contract code itself - and then the SDK - when it 'knows' the it it evaluating the state from the scratch - calls the init/'constructor' function first - and then moves to evaluating the interactions.

What do you think?

**Comment by koonopek** [comment]
> Well, the same way you can verify the initial state...(as it is kept in the contract deployment transaction).
Can I access it within smart-contract code?

Exactly, and we should to run constructor always once, the should be no other way to init contract state.

I'm currently writing smart contract which `Offer` which can have several stages `PENDING`->`ACCEPTED_BY_BUYER` -> ... ->`FINALIZED`, now I'm not able to assert (from within smart contract) that OFFER passed all this stages, and was not initialised with state appropriate to  `ACCEPTED_BY_BUYER` stage for example. Of course I can check it by analysing all interactions, however it is not good DX(developer experience) and is less secure in my opinion.

**Comment by ppedziwiatr** [comment]
If contract has a 'special' init function (name TBA), the SDK will be responsible for calling such function before evaluating interactions with the state defined in the deployment transaction)

**Comment by ppedziwiatr** [comment]
how about `WOOT_HACK_WOOT_init` ;-)

now, being serious - I would use a convention that good-old angular.js was using for storing its internal stuff - so sth. like
1. `$$init(initialState)`
2. `$$_init(initialState)`
3. or maybe `__init(initalState)`

**Comment by ppedziwiatr** [comment]
Not sure how to secure against manual init calls from the contract code....from this perspective it would probably the best to keep the init function in a separate arweave transaction - so that it couldn't be called from the contract itself.

So here's an alternative: consider storing the init function code in the 'data' field of the contract transaction (instead of the initial state json, that is usually kept there). This would nicely separate the standard contract code from the initialization code (and I believe would be more secure - the user would have no means of calling the init function manually - either from the contract code or by creating an interaction)

**Comment by koonopek** [comment]
For me 3. looks the best, this is convention from python I think, pretty popular lang :) Maybe even `__init__(initialState)`.
Maybe we could ask community :)

> So here's an alternative: consider storing the init function code in the 'data' field of the contract transaction (instead of the initial state json, that is usually kept there). This would nicely separate the standard contract code from the initialization code (and I believe would be more secure - the user would have no means of calling the init function manually - either from the contract code or by creating an interaction)

Sound perfect. So:
1. The interaction `{function: '__init__'}` would check if it is first interaction, if so it will pass deploySourceTx.data as args?
2. Then everything works normally
3.  If user call as first interaction for example `{function: 'blabal`}` he will get error('call __init__ first`), because he haven't called `{function: '__init__'}` before?

**Comment by koonopek** [comment]
On balance:
1. Support calling `__init` (or something like that) function from SDK
2. `__init` function is stored within contract
3. If contract doesn't expose `__init` function, just don't call it
4. Throw error on interactions trying to call `__init`
5. Calling constructor is possible many times, but only from within contract code
6.  if `__init` function is exposed `initialState` is passed as argument
7.  if `__init` function is NOT exposed use `initialState` as it is working now
8.  if `__init` function fails don't deploy contract (i'm not sure is this good idea, but logical)

**Comment by ppedziwiatr** [comment]
Approved :-)

**Comment by koonopek** [comment]
I'm thinking about 3 - How we should deduce if smart-contract is using `constructor`?
1. add field to manifest `{constructor: true}`
(+) works with old contracts
(+) the simplest 
(-) dev has to provide value on deployment

2. parse ast of contract
(-) may take too much time if contract is bloated
(+) works in all cases

3. Be naive and try to call `__init` if function doesn't exist don't fail. if function exists and fails then fail.
(+) simple
(-) doesnt work on old contracts which, already has method `__init` to surpass we could event use more sophisticated name.

I would choose 1.
What is your opinion @ppedziwiatr

**Comment by ppedziwiatr** [comment]
Let's be explicit here - option numer 1!

**Comment by ppedziwiatr** [comment]
released in https://github.com/warp-contracts/warp/releases/tag/1.2.56
