### ISSUE TITLE
Error while reading contract state: unreachable

### ISSUE THREAD

**Issue by marslab2022** [warp-contracts/warp#351]
When calling `readState()`, it occurs the error(warp sdk version: 1.2.11): 
![f1bcfc40-a2e5-4d71-bba3-64ee31e7f48c](https://user-images.githubusercontent.com/112821387/219610958-74fb50e5-8eae-4bc3-86b5-72d361fcf781.jpeg)

And it also occurs with warpCLI:
![LuKmrmDYTc](https://user-images.githubusercontent.com/112821387/219611298-bae57353-69d7-4da8-a3bd-7fa28fe4bbac.jpg)

But in sonAR, the state shows correctly.
https://sonar.warp.cc/#/app/contract/4Kd5SIvLHv6f8-wLRvZpXTLEKaGc3jjNwXhiQj2VZv0#state

Contract code: https://github.com/marslab2022/wrc/tree/master/contracts/atomic-nft

**Comment by asiaziola** [comment]
as discussed on Discord - types in the initial state were incompatible with the contract code (numbers marked as strings). Due to this fact, Rust contract could not be executed correctly.
