### ISSUE TITLE
fix: Fix flaky tests

### ISSUE THREAD

**Issue by koonopek** [warp-contracts/warp#360]
This test, sometimes pass sometimes. Root cause might be arlocal, but doesn't have to be :)
Example: https://github.com/warp-contracts/warp/actions/runs/4253503155

**Comment by ppedziwiatr** [comment]
I agree that regression tests are still flaky (as still some tested contracts use unsafeClient), but the above example fails for this reason
<img width="902" alt="image" src="https://user-images.githubusercontent.com/84311757/221199828-ace7f86c-1bf4-44df-9ffe-c3a5bcee5caa.png">

**Comment by koonopek** [comment]
Ups, thanks cant reproduce locally

Pozdrawiam,
Michał Konopka

pt., 24 lut 2023, 15:13 użytkownik just_ppe ***@***.***>
napisał:

**Comment by koonopek** [comment]
Issue is cause by too high concurenncy, closing for now
