### ISSUE TITLE
fix: unable to createSource with JWKInterface wallet

### ISSUE THREAD

**Issue by dtfiedler** [warp-contracts/warp#376]
## Details
-  `"warp-contracts": "^1.3.0"`
 - `"warp-contracts-plugin-deploy": "^1.0.1"`

Unable to `createSource` with local JWKInterface wallet.

```
  const newLocalSourceCodeJS = fs.readFileSync(
    path.join(__dirname, 'contract.js'),
    'utf8',
  );

  // Create the evolved source code tx
  const evolveSrcTx = await warp.createSource(
    { src: newLocalSourceCodeJS },
    wallet,
    true --> Expected 2 arguments, but got 3.
  );
```
and without `disableBundling` set:
```
Error: Only Signer wallet type is allowed when bundling is enabled.
    at SourceImpl.createSource (/Users/dylanfiedler/Documents/ario/arns-pilot/node_modules/warp-contracts-plugin-deploy/src/deploy/impl/SourceImpl.ts:51:13)
    at CreateContractImpl.createSource (/Users/dylanfiedler/Documents/ario/arns-pilot/node_modules/warp-contracts-plugin-deploy/src/deploy/impl/CreateContractImpl.ts:181:24)
    at Warp.createSource (/Users/dylanfiedler/Documents/ario/arns-pilot/node_modules/warp-contracts/src/core/Warp.ts:123:38)
    at /Users/dylanfiedler/Documents/ario/arns-pilot/src/tools/evolve-contract.ts:46:34
````

The `DeployPlugin` was updated to allow `disableBundling` to be provided on `createSource` ([here](https://github.com/warp-contracts/warp-contracts-plugins/blob/main/warp-contracts-plugin-deploy/src/deploy/impl/SourceImpl.ts#L24-L33)), but doesn't appear to be in `Warp.ts` [here](https://github.com/warp-contracts/warp/blob/main/src/core/Warp.ts#L119-L124) which should be passed to `Source.ts` [here](https://github.com/warp-contracts/warp/blob/main/src/contract/deploy/Source.ts#L27).

**Comment by ppedziwiatr** [comment]
Thanks for the report, @asiaziola will take a look!

**Comment by ppedziwiatr** [comment]
hey @dtfiedler , can you please check version `1.3.1`?

**Comment by dtfiedler** [comment]
works as expected in `1.3.1` - thank you @ppedziwiatr and @asiaziola!
