### ISSUE TITLE
[BUG] warp sdk 1.3.3 readState error with webpack5

### ISSUE THREAD

**Issue by marslab2022** [warp-contracts/warp#385]
**Describe the bug**
Updated to warp sdk 1.3.3 from 1.2.20, and when calling readState
![image](https://user-images.githubusercontent.com/112821387/229688936-b81a8ea7-80dd-4f16-abdc-b36bed6f0788.png)
Got error in console
![image](https://user-images.githubusercontent.com/112821387/229689081-09d09e5c-e1e0-4dc7-9e0a-bed32aeb074d.png)

**To Reproduce**
GH Example: https://github.com/marslab2022/test_warp_v3
```bash
npm install
npm start
```
press F12 to open console, will display the error.

**Expected behavior**
should no error and print contract state in console.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac v11.4
 - Node.js v16.10.0
 - warp-contracts SDK version v1.3.3
 - warp-contracts plugins being used (+ versions)
 - Browser chrome 
 - Version 110.0.5481.100 (x86_64)

**Additional context**

**Comment by asiaziola** [comment]
Hey @marslab2022 ! Have you tried importing from `warp-contracts/web`?

**Comment by asiaziola** [comment]
I've just tested it in your github repository and it seems to work fine. Here is a repo with sample usage for several web bundlers including webpack5 https://github.com/warp-contracts/bundlers

**Comment by marslab2022** [comment]
> warp-contracts/web

Thanks. With `warp-contracts/web` it works fine!
