### ISSUE TITLE
[BUG] Wrong import path

### ISSUE THREAD

**Issue by ropats16** [warp-contracts/warp#395]
**Describe the bug**
Unable to build package due to incorrect import path for Tag in the following file `warp-contracts/lib/types/contract/deploy/DataItem.d.ts:2:21` as `import { Tag } from 'utils/types/arweave-types';`

**To Reproduce**
NA

**Expected behavior**
Should not throw the error if the path `import { Tag } from '../../utils/types/arweave-types';`

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: NA
 - Node.js version `v18.12.0`
 - warp-contracts SDK version `1.4.0`
 - warp-contracts plugins being used (+ versions) NA
 - Browser NA
 - Version NA

**Additional context**
NA

**Comment by asiaziola** [comment]
import has been fixed in `warp-contracts@1.4.1`
