### ISSUE TITLE
[FEATURE] Validate 'handle' function format before the deployment of the js contracts

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#400]
**Is your feature request related to a problem? Please describe.**
While bundling a contract written in TS, one can run into issues related to transpiling, treeshaking, etc. - which results in an incorrent format of the `handle` function (i.e. the main function of the contract - that SDK is calling during state evaluation).
Deploying such contract makes no sense, as it fails to evaluate.

**Describe the solution you'd like**
Some sort of validation (at least of the `handle` function) should be performed during contract deployment.
A validation error should prevent from sending the transaction.

**Describe alternatives you've considered**
Reading https://docs.warp.cc/tutorials/pst/writing-pst-contract/contract-source#-bundling-contract docs? ;-)

**Additional context**
Twitter thread: https://twitter.com/K4y1s/status/1649372523757285376

**Comment by ppedziwiatr** [comment]
idea: consider using one of the ASTs - https://www.digitalocean.com/community/tutorials/js-traversing-ast
Verify performance for very large contracts (like https://sonar.warp.cc/#/app/contract/f86Qw3vp6TlgxI3mABFnWDQNqR8mPVkVTBN04hwywqc#code)

**Comment by ppedziwiatr** [comment]
using acorn and simple script:
```js
const acorn = require("acorn");
const fs = require("fs");
const src = fs.readFileSync("../src/__tests__/integration/data/very-complicated-contract.js", "utf-8");

console.time("validating");
const ast = acorn.parse(src, {ecmaVersion: 2020});
const handleFunction = ast.body.find(n => n.type === 'FunctionDeclaration' && n.id.name === 'handle');
console.dir(handleFunction, {depth: 2});

const valid = handleFunction
    && handleFunction.params.length == 2
    && handleFunction.params[0].name == 'state'
    && handleFunction.params[1].name == 'action';

console.log('valid?', valid);

console.timeEnd("validating")
```

on my current potato (`i7-4810MQ`):
```
valid? true
validating: 124.525ms
```

The test contract is https://github.com/warp-contracts/warp/blob/main/src/__tests__/integration/data/very-complicated-contract.js

**Comment by kay-is** [comment]
I had a TypeScript contract where I tried all of these these:

    function handle(state, action) {}
    
    export function handle(state, action) {}

    const handle = (state, action) => {} // which I settled on

    export const handle = (state, action) => {}

Then I ran it through Vite

Where I used this config:

```
export default defineConfig({
  build: {
    outDir: "dist/contract",
    minify: false, // also tried true, which is the default
    rollupOptions: {
      treeshake: false, //also tried true, which is the default 
    },
    lib: {
      name: "warpContract",
      entry: "src/contract/index.ts",
      formats: ["cjs"], //also tried "iife" and "es"
      fileName: "bundle",
    },
  },
})
```

The settings in the comments didn't work.

Would be cool to get the optimal config that works with the "es" setting and (at least partial?) Tree shaking and minification 😎

**Comment by ppedziwiatr** [comment]
Oh, ok, I admit we're staying away from the meta-frameworks :-) not sure which build system Vite is using, I believe some combination of both esbuild and rollup?

Anyway, so far we've been always bundling with esbuild 'directly' - and there weren't any issues.

The first - basic example - is in the Warp Academy 
https://docs.warp.cc/tutorials/pst/writing-pst-contract/contract-source#-bundling-contract

Another example:
https://github.com/redstone-finance/redstone-oracles-monorepo/blob/main/packages/oracles-smartweave-contracts/src/contracts/redstone-oracle-registry/redstone-oracle-registry.contract.ts
https://github.com/redstone-finance/redstone-oracles-monorepo/blob/main/packages/oracles-smartweave-contracts/scripts/build.js

I believe weavedb is also bundling their contract, though it's written in js (somewhere around https://github.com/weavedb/weavedb/blob/master/sdk/contracts/weavedb/contract.js)

**Comment by kay-is** [comment]
I would assume, the easiest way to get basic contract format validation is to do a dry run of `readState` on the source before it's deployed 🤔

**Comment by ppedziwiatr** [comment]
Yup, that's also an option.
@kay-is do you remember what error did you get? sth similar to
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/84311757/234596043-18361c42-30b1-4c7b-b493-c5abf7d0550a.png">
?

Do you happen to have the 'wrong' sources? I would add them to the test cases...

**Comment by kay-is** [comment]
From TypeScript

    export function handle() {}

to CJS

    "use strict";
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    function handle() {
    }
    exports.handle = handle;

Error

```
ReferenceError: exports is not defined
    at eval (eval at create (HandlerExecutorFactory.ts:228:34), <anonymous>:9:23)
    at HandlerExecutorFactory.create (HandlerExecutorFactory.ts:230:13)
    at CacheableExecutorFactory.create (CacheableExecutorFactory.ts:26:42)
    at HandlerBasedContract.createExecutionContext (HandlerBasedContract.ts:543:50)
    at async HandlerBasedContract.readState (HandlerBasedContract.ts:167:32)
    at async MyContract.readState (contract.ts:33:29)

```

To IIFE

    var library = function(exports) {
      "use strict";
      function handle() {
      }
      exports.handle = handle;
      Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
      return exports;
    }({});
 
Error

    ReferenceError: handle is not defined
        at eval (eval at create (HandlerExecutorFactory.ts:228:34), <anonymous>:17:5)
        at HandlerExecutorFactory.create (HandlerExecutorFactory.ts:230:13)
        at CacheableExecutorFactory.create (CacheableExecutorFactory.ts:26:42)
        at HandlerBasedContract.createExecutionContext (HandlerBasedContract.ts:543:50)
        at async HandlerBasedContract.readState (HandlerBasedContract.ts:167:32)
        at async MyContract.readState (contract.ts:33:29)

To ES

    function handle() {
    }
    export {
      handle
    };

Error

    SyntaxError: Unexpected token 'export'
        at new Function (<anonymous>)
        at HandlerExecutorFactory.create (HandlerExecutorFactory.ts:228:34)
        at CacheableExecutorFactory.create (CacheableExecutorFactory.ts:26:42)
        at HandlerBasedContract.createExecutionContext (HandlerBasedContract.ts:543:50)
        at async HandlerBasedContract.readState (HandlerBasedContract.ts:167:32)
        at async MyContract.readState (contract.ts:33:29)

To UMD

    ;(function (global, factory) {
      typeof exports === "object" && typeof module !== "undefined"
        ? factory(exports)
        : typeof define === "function" && define.amd
        ? define(["exports"], factory)
        : ((global =
            typeof globalThis !== "undefined" ? globalThis : global || self),
          factory((global.library = {})))
    })(this, function (exports2) {
      "use strict"
      function handle() {}
      exports2.handle = handle
      Object.defineProperty(exports2, Symbol.toStringTag, { value: "Module" })
    })

Error

    ReferenceError: handle is not defined
        at eval (eval at create (HandlerExecutorFactory.ts:228:34), <anonymous>:18:5)
        at HandlerExecutorFactory.create (HandlerExecutorFactory.ts:230:13)
        at CacheableExecutorFactory.create (CacheableExecutorFactory.ts:26:42)
        at HandlerBasedContract.createExecutionContext (HandlerBasedContract.ts:543:50)
        at async HandlerBasedContract.readState (HandlerBasedContract.ts:167:32)
        at async MyContract.readState (contract.ts:33:29)

From TypeScript

function handle() {}

To CJS

    "use strict";
    function handle() {
    }

No Error

To IIFE

    (function() {
      "use strict";
      function handle() {
      }
    })();

No Error

To ES

    function handle() {
    }

No Error

To UMD

    (function(factory) {
      typeof define === "function" && define.amd ? define(factory) : factory();
    })(function() {
      "use strict";
      function handle() {
      }
    });

Error

    ReferenceError: handle is not defined
        at eval (eval at create (HandlerExecutorFactory.ts:228:34), <anonymous>:16:5)
        at HandlerExecutorFactory.create (HandlerExecutorFactory.ts:230:13)
        at CacheableExecutorFactory.create (CacheableExecutorFactory.ts:26:42)
        at HandlerBasedContract.createExecutionContext (HandlerBasedContract.ts:543:50)
        at async HandlerBasedContract.readState (HandlerBasedContract.ts:167:32)
        at async MyContract.readState (contract.ts:33:29)

**Comment by kay-is** [comment]
btw.

I got rid of the "exports" error this before deploying: 

```javascript
contractSource = `exports = {};${contractSource}global.handle = exports.handle;`
```

That way I can `export` the `handle` function in TypeScript and import it in my tests.

**Comment by ppedziwiatr** [comment]
warp-contracts 1.4.5, deploy-plugin 1.0.8
