### ISSUE TITLE
[BUG] Failed to retrieve the stamp contract status from arweave.net.

### ISSUE THREAD

**Issue by xiaojay** [warp-contracts/warp#419]
**Describe the bug**

I attempted to retrieve the stamp contract (https://sonar.warp.cc/?#/app/contract/TlqASNDLA1Uh8yFiH-BzR_1FDag4s735F3PoUFEv2Mo) status from the arweave.net gateway.

the script located at 
https://github.com/xiaojay/warptest/blob/main/src/stamp_state.ts

got error：

_2023-05-28T14:30:02.217Z INFO [ArweaveGatewayBundledContractDefinitionLoader] Contract definition loaded in: 699ms []
readState error: Error: Interaction fNRBubM941UdtaGCelUHceMVWKRudFn3ZwETsk2HqBc is not sequenced by sequencer aborting. Only Sequenced transactions are supported by loader ArweaveGatewayBundledInteractionLoader
    at ArweaveGatewayBundledInteractionLoader.attachSequencerDataToInteraction (/home/ubuntu/warptest/node_modules/warp-contracts/src/core/modules/impl/ArweaveGatewayBundledInteractionLoader.ts:177:13)
    at /home/ubuntu/warptest/node_modules/warp-contracts/src/core/modules/impl/ArweaveGatewayBundledInteractionLoader.ts:119:34
    at Array.map (<anonymous>)
    at ArweaveGatewayBundledInteractionLoader.load (/home/ubuntu/warptest/node_modules/warp-contracts/src/core/modules/impl/ArweaveGatewayBundledInteractionLoader.ts:119:8)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HandlerBasedContract.createExecutionContext (/home/ubuntu/warptest/node_modules/warp-contracts/src/contract/HandlerBasedContract.ts:496:30)
    at async HandlerBasedContract.readState (/home/ubuntu/warptest/node_modules/warp-contracts/src/contract/HandlerBasedContract.ts:164:32) contractId: TlqASNDLA1Uh8yFiH-BzR_1FDag4s735F3PoUFEv2Mo_

The reason for this issue seems to be that the stamp tx used the "Sequencer-Prev-Sort-Key" tag to indicate the previous tx's sort key, while the ArweaveGatewayBundledInteractionLoader.ts validates tx using the "Sequencer-Last-Sort-Key” tag (https://github.com/warp-contracts/warp/blob/db83105425ceb23c342b52661a98676694cf28d7/src/core/modules/impl/ArweaveGatewayBundledInteractionLoader.ts#L163), causing the transaction verification to fail. 

I believe this is a backward compatibility issue and both tag "Sequencer-Prev-Sort-Key" and "Sequencer-Last-Sort-Key" should be supported during verification.

**To Reproduce**
https://github.com/xiaojay/warptest/blob/main/src/stamp_state.ts

**Expected behavior**
The contract state obtained from the arweave.net gateway should be consistent with the one obtained from the warp gateway.

**Screenshots**

https://arseed.web3infra.dev/TDx2_EHWOf4Xri13ObsIX3ymFKe8I8609EZurqfXjnY

**Desktop (please complete the following information):**
 - OS:  ubuntu
 - Node.js v18.14.2
 - warp-contracts SDK version: v1.4.9
 - warp-contracts plugins being used (+ versions): no
 - Browser [e.g. chrome, safari]: no
 - Version [e.g. 22]: no

**Additional context**
no

**Comment by ppedziwiatr** [comment]
Thanks @xiaojay for the report and analysis, we will look into this issue

**Comment by xiaojay** [comment]
yes, I have same issue with arweave.net gateway, hope they cloud solve it

**Comment by vilenarios** [comment]
We have reindexed the bundle that contained the above data item.  It is now available on arweave.net/graphql

**Comment by ppedziwiatr** [comment]
some more issues with other data-items -> Discord :-)

**Comment by ppedziwiatr** [comment]
`1.4.11`
