### ISSUE TITLE
[BUG] Failed to evaluate the state of U contract by warp sdk

### ISSUE THREAD

**Issue by xiaojay** [warp-contracts/warp#436]
**Describe the bug**
Failed to evaluate the state of U contract by warp sdk locally

**To Reproduce**
the evaluate script is https://github.com/xiaojay/warptest/blob/main/src/u2.ts

**Expected behavior**

**Screenshots**

https://6xyaozsp5s25dqfthiwpuf655bkf2fpuvg3waq7eqw3dl2kw6z5a.arweave.net/9fAHZk_stdHAszos-hfd6FRdFfSpt2BD5IW2NelW9no

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Node.js version: v18.14.2
 - warp-contracts SDK version: 1.4.14
 - warp-contracts plugins being used: no
 - Browser: no
 - Version: no

**Additional context**
I think the exception is raised by the related contract i-2T9huigZODi0XnvN6ZegJwc3Z-F4i3PCsAt4_ppyw set a ""useConstructor":true" evaluate option, but don not have __init func.
I walkaround this issue  by this commit https://github.com/xiaojay/warp/commit/72d6dfba6cfaa4a3c794c201ccce2a0d1be59643

**Comment by ppedziwiatr** [comment]
fixed in 1.4.18
