### ISSUE TITLE
[BUG] Error when running Warp in a Web Worker

### ISSUE THREAD

**Issue by elliotsayes** [warp-contracts/warp#451]
**Describe the bug**
When running warp in a Web Worker, the following error is thrown:
<img width="561" alt="Screenshot 2023-08-07 at 2 13 28 PM" src="https://github.com/warp-contracts/warp/assets/7699058/6256159c-34f2-476e-ba5d-dd33c6c0ce7a">

**To Reproduce**
Create a warp client in a web worker

**Expected behavior**
Should not throw an error

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: macOS (m1)
 - Node.js version: LTS
 - warp-contracts SDK version: 1.4.14
 - warp-contracts plugins being used (+ versions): N/A
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 115.0.5790.170

**Additional context**
Discord discussion: https://discord.com/channels/1103577987007397919/1103964286600093788/1136228353968439296

**Comment by Tadeuchi** [comment]
Please check the latest SDK version: 1.4.16
It should resolve the issue.

**Comment by elliotsayes** [comment]
Works great, thank you !!
