### ISSUE TITLE
[FEATURE] Allow Warp to register other L2 TXs

### ISSUE THREAD

**Issue by twilson63** [warp-contracts/warp#477]
**Is your feature request related to a problem? Please describe.**
Support Ardrive Turbo uploaded data to be sequenced.

**Describe the solution you'd like**

```
await Warp.register(TX_ID, 'ardrive')
```

**Describe alternatives you've considered**
The only alternative is to use Irys, but allowing other bundling services to register assets will provide flexibility

**Additional context**
Turbo Docs - https://docs.ardrive.io/

**Comment by ppedziwiatr** [comment]
Hey, thanks for the feature request, we will discuss/analyse this internally.

**Comment by ppedziwiatr** [comment]
@twilson63  can you please send some examples of such data-items/transactions?

The obivious problem is how to order such transaction in relation to the L1 and 'native' Warp L2 transactions.

I guess the simples solution would be to assing the sequencer/sortKey and the time of registering, but with some hint that the transaction should not be posted to Bundlr... @janekolszak , WDYT?

**Comment by ppedziwiatr** [comment]
Also...I believe that would still need to create a nested bundle and post it to Arweave - as the data assigned by the sequencer has to be stored on chain (i.e. on Arweave).

**Comment by janekolszak** [comment]
**I think this is a good idea, but it needs a new feature from Irys.** 

Warp's sequencer can't just accept `txId`, because it's not a proof the tx is actually accepted by Irys. 
We'd need a signed receipt (`txId` should be a part of the signature).

This way every sequencer node could check that the tx with this `txId` is uploaded to Irys without doing any requests. This is needed when registering interaction, but also upon sequencer block verification. There's an REST API to check if tx is on Irys, but it's not possible to make any requests during block verification.

**Comment by ppedziwiatr** [comment]
@janekolszak you mean from ar.io? :-) Turbo is ar.io's bundler...

**Comment by janekolszak** [comment]
yes, sorry. So it should be easier ;)

**Comment by twilson63** [comment]
Here is an example:

https://viewblock.io/arweave/tx/Fc4XxUVxk-qPyrfA0eZ1NSFxfeUrokzDYqKX1ysAss4

You will notice it is bundled by ardrive turbo's bundler

**Comment by vilenarios** [comment]
Thank you Tom!  Yes, our upload service can be found at https://upload.ardrive.io (https://upload.ardrive.io/api-docs) or our unified uploading/payment url at https://turbo.ardrive.io.  

Clients that complete upload posts will receive the transaction ID for the data item.  This data item transaction is immediately indexed within the arweave.net GQL and its data is also available in the arweave.net cache.  Not sure if this would help you verify that the transaction ID is valid.

**Comment by twilson63** [comment]
@ppedziwiatr - Registering Contracts, just like with Irys.

ardrive upload-file ...atomic asset contract...
`warp.register(CONTRACT_TX_ID, 'ardrive')`

**Comment by jajablinky** [comment]
Yes please.

**Comment by samcamwilliams** [comment]
> Warp's sequencer can't just accept txId, because it's not a proof the tx is actually accepted by Irys.

@vilenarios -- does Turbo support signed receipts? I believe that Iris does this, and it would make a lot of sense for Warp not to accept TXs without it.

If Turbo does support receipts, though, it would be incredible to see this in production! Issuing smart contracts and interacting with them, while paying in fiat, could be a 10x improvement in UX.

Sam

**Comment by asiaziola** [comment]
Hey @twilson63 - check out `warp-contracts@1.4.23`, it enables registration of contracts deployed using other providers than Irys. Here is release note for this change https://github.com/warp-contracts/warp/releases/tag/v1.4.23 (this change requires upgrading `warp-contracts-plugin-deploy` to `1.0.11`. Let me now, if that works for you.
