### ISSUE TITLE
[BUG] - `viewState` with `sortKey` not using proper block information

### ISSUE THREAD

**Issue by dtfiedler** [warp-contracts/warp#511]
**Describe the bug**
When providing a sortKey for a read interaction - the global `SmartWeave` object uses the most recent block height information, instead of the block height specified by the `sortKey.`

**To Reproduce**
Run any `viewState` interaction on a contract that uses a global SmartWeave object in the read interaction execution. 

**Expected behavior**
The block information used for evaluation of read interactions matches the provided `sortKey`

**Desktop (please complete the following information):**
 - OS: [e.g. Linux] - Linux
 - Node.js version - 18.17.1
 - warp-contracts SDK version - 1.4.36

**Additional context**
Related to https://github.com/warp-contracts/warp/issues/504

**Comment by dtfiedler** [comment]
https://github.com/warp-contracts/warp/pull/512

**Comment by asiaziola** [comment]
Released in 1.4.37
