### ISSUE TITLE
[BUG] - absolute path breaking builds

### ISSUE THREAD

**Issue by dtfiedler** [warp-contracts/warp#523]
**Describe the bug**
When building with warp-contracts>1.4.39 - get the following error

```sh
node_modules/warp-contracts/lib/types/core/modules/impl/HandlerExecutorFactory.d.ts:12:21 - error TS2307: Cannot find module 'utils/types/mutually-exclusive' or its corresponding type declarations.

12 import { XOR } from 'utils/types/mutually-exclusive';
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/warp-contracts/lib/types/core/mo
```

**To Reproduce**
Install warp-contracts@v1.4.43

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es2021",
    "module": "CommonJS",
    "moduleResolution": "node",
  }
}
```

```typescript
import { WarpFactory } from 'warp-contracts'
```

**Expected behavior**
Routes are all relative and builds work as expected

**Desktop (please complete the following information):**
 - OS: [e.g. Linux] - macOS
 - Node.js version - 18.17.1
 - warp-contracts SDK version - 1.4.43

**Additional context**
Github action build error here https://github.com/ar-io/arns-service/actions/runs/9018958323/job/24780910601

**Comment by ppedziwiatr** [comment]
released in 1.4.44
